pub const DEFAULT_DIGITS_AND_SYMBOLS: [(char, &str); 43] = [
    ('0', "Zero"),
    ('1', "One"),
    ('2', "Two"),
    ('3', "Three"),
    ('4', "Four"),
    ('5', "Five"),
    ('6', "Six"),
    ('7', "Seven"),
    ('8', "Eight"),
    ('9', "Nine"),
    (' ', "Space"),
    ('!', "Exclamation"),
    ('"', "DoubleQuote"),
    ('#', "Hash"),
    ('$', "Dollars"),
    ('%', "Percent"),
    ('&', "Ampersand"),
    ('(', "LeftParens"),
    (')', "RightParens"),
    ('*', "Asterisk"),
    ('+', "Plus"),
    (',', "Comma"),
    ('-', "Dash"),
    ('.', "Period"),
    ('/', "ForeSlash"),
    (':', "Colon"),
    (';', "SemiColon"),
    ('<', "LessThan"),
    ('=', "Equals"),
    ('>', "GreaterThan"),
    ('?', "Question"),
    ('@', "At"),
    ('[', "LeftBracket"),
    ('\'', "SingleQuote"),
    ('\\', "BackSlash"),
    (']', "RightBracket"),
    ('^', "Caret"),
    ('_', "Underscore"),
    ('`', "Backtick"),
    ('{', "LeftBrace"),
    ('|', "Pipe"),
    ('}', "RightBrace"),
    ('~', "Tilde"),
];

// Los Angeles Police Department (LAPD)
// Association of Public-Safety Communications Officials-International (APCO)
pub const LAPD_ALPHABET: [(char, &str); 27] = [
    ('a', "Adam"),
    ('b', "Boy"),
    ('c', "Charles"),
    ('d', "David"),
    ('e', "Edward"),
    ('f', "Frank"),
    ('g', "George"),
    ('h', "Henry"),
    ('i', "Ida"),
    ('j', "John"),
    ('k', "King"),
    ('l', "Lincoln"),
    ('m', "Mary"),
    ('n', "Nora"),
    ('o', "Ocean"),
    ('p', "Paul"),
    ('q', "Queen"),
    ('r', "Robert"),
    ('s', "Sam"),
    ('t', "Tom"),
    ('u', "Union"),
    ('v', "Victor"),
    ('w', "William"),
    ('x', "X-ray"),
    ('y', "Young"),
    ('z', "Zebra"),
    ('9', "Niner"),
];

// North Atlantic Treaty Organization (NATO)
// International Civil Aviation Organization (ICAO)
// International Radiotelephony Spelling Alphabet (IRSA)
pub const NATO_ALPHABET: [(char, &str); 30] = [
    ('a', "Alfa"),
    ('b', "Bravo"),
    ('c', "Charlie"),
    ('d', "Delta"),
    ('e', "Echo"),
    ('f', "Foxtrot"),
    ('g', "Golf"),
    ('h', "Hotel"),
    ('i', "India"),
    ('j', "Juliett"),
    ('k', "Kilo"),
    ('l', "Lima"),
    ('m', "Mike"),
    ('n', "November"),
    ('o', "Oscar"),
    ('p', "Papa"),
    ('q', "Quebec"),
    ('r', "Romeo"),
    ('s', "Sierra"),
    ('t', "Tango"),
    ('u', "Uniform"),
    ('v', "Victor"),
    ('w', "Whiskey"),
    ('x', "X-ray"),
    ('y', "Yankee"),
    ('z', "Zulu"),
    ('3', "Tree"),
    ('4', "Fower"),
    ('5', "Fife"),
    ('9', "Niner"),
];

// United States Financial Industry
pub const US_FINANCIAL_ALPHABET: [(char, &str); 26] = [
    ('a', "Adam"),
    ('b', "Bob"),
    ('c', "Carol"),
    ('d', "David"),
    ('e', "Eddie"),
    ('f', "Frank"),
    ('g', "George"),
    ('h', "Harry"),
    ('i', "Ike"),
    ('j', "Jim"),
    ('k', "Kenny"),
    ('l', "Larry"),
    ('m', "Mary"),
    ('n', "Nancy"),
    ('o', "Oliver"),
    ('p', "Peter"),
    ('q', "Quincy"),
    ('r', "Roger"),
    ('s', "Sam"),
    ('t', "Thomas"),
    ('u', "Uncle"),
    ('v', "Vincent"),
    ('w', "William"),
    ('x', "Xavier"),
    ('y', "Yogi"),
    ('z', "Zachary"),
];
