blank_issues_enabled: false
contact_links:
  - name: Questions and community conversations
    url: https://github.com/EarthmanMuons/spellout/discussions
    about: Please use discussions to ask and answer questions.
