blank_issues_enabled: false
contact_links:
  - name: Questions and community conversations
    url: https://github.com/EarthmanMuons/rustops-blueprint/discussions
    about: Please use discussions to ask and answer questions.
