name: draft-release
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
jobs:
  create_release:
    name: create draft release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.gh_release.outputs.upload_url }}
      url: ${{ steps.gh_release.outputs.url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - id: gh_release
        name: Create a new GitHub draft release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          draft: true
          generate_release_notes: true
      - name: Annotate workflow run with draft release URL
        run: 'echo "### :shipit: Opened draft release for: [spellout ${{ github.ref_name }}](${{ steps.gh_release.outputs.url }})" >> "$GITHUB_STEP_SUMMARY"'
  upload_assets:
    name: upload release assets
    needs:
      - create_release
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            build_tool: cargo
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            build_tool: cargo
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cross
          - target: x86_64-apple-darwin
            os: macos-latest
            build_tool: cargo
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build_tool: cargo
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cargo
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y musl-tools
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@2656b87321093db1cb55fbd73183d195214fdfd1
        with:
          shared-key: stable-ubuntu-latest
        timeout-minutes: 5
      - uses: taiki-e/install-action@d3712f40a2bae95e3ce25a24f82a795ed3df0f1c
        if: matrix.os == 'ubuntu-latest'
        name: Install cross
        with:
          tool: cross
      - name: Building release assets
        run: |-
          if [[ "${{ matrix.build_tool }}" == "cross" ]]; then
          	cargo xtask dist --target "${{ matrix.target }}" --cross
          else
          	cargo xtask dist --target "${{ matrix.target }}"
          fi
      - name: Uploading release assets
        run: "if [[ \"${{ matrix.os }}\" == \"windows-latest\" ]]; then\n  extension=\"zip\"\nelse\n  extension=\"tar.gz\" \nfi\nfilename=\"spellout-${GITHUB_REF_NAME:1}-${{ matrix.target }}.${extension}\"\n\necho \"Uploading ${filename} to: ${{ needs.create_release.outputs.upload_url }}\"\ngh release upload \"$GITHUB_REF_NAME\" \"target/dist/${filename}\"\n\necho \":arrow_up: Uploaded release asset ${filename}\" >>\"$GITHUB_STEP_SUMMARY\""
