name: labeler
"on":
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  label_pr:
    name: label pr
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request based on paths of changed files
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          dot: true
