name: on schedule weekly

on:
  schedule:
    # Run every Monday at 7:45am UTC.
    - cron: 45 7 * * 1

  # Allow manually running this workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_rust_beta:
    name: check rust / beta
    uses: EarthmanMuons/reusable-workflows/.github/workflows/check-rust-beta.yml@main

  check_rust_miri:
    name: check rust / miri
    uses: EarthmanMuons/reusable-workflows/.github/workflows/check-rust-miri.yml@main
